spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev
  mvc:
    format:
      date: yyyy-MM-dd
  messages:
    basename: i18n/messages_zh_CN
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dawdle.blog.pojo
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

comment.avatar: /images/male.png